### ISSUE TITLE
Adding boss killcounts

### ISSUE THREAD

**Issue by Moelanz** [elbojoloco/runescape-hiscores#1]
Oldschool runescape now allows you to see boss/minigame killcounts, can this be added please?

**Comment by elbojoloco** [comment]
@Moelanz I'm not actively maintaining this package, if I have some time I might look into this but until then feel free to submit a PR for the change :)

**Comment by Moelanz** [comment]
https://github.com/elbojoloco/runescape-hiscores/pull/2
